const OWNER = 'nightowlhoothoot83-create';

export const AUTOMATIONS = [
  { id:'site-contract-integrity', group:'site-adsense', label:'Site contract & visual health', description:'Read-only site, build and regression checks for the AdSense sites.', repo:'ADG-MONITOR-V4', workflow:'site-contract-integrity.yml', ref:'main', safeRun:true, schedulable:false, scheduleLocked:true, defaultFrequency:'6h', nativeSchedule:'Every 6 hours · GitHub managed', risk:'low' },
  { id:'ads-txt-monitor', group:'site-adsense', label:'AdSense ads.txt monitor', description:'Checks the canonical ads.txt record on Wheel Name Picker, MyCalendarTools and MyCalcTools.', repo:'Raven-Sharp-QA-Agent', workflow:'ads-txt-monitor.yml', ref:'main', safeRun:true, schedulable:false, scheduleLocked:true, defaultFrequency:'6h', nativeSchedule:'Every 6 hours · GitHub managed', risk:'low' },
  { id:'site-guardian', group:'site-adsense', label:'Raven Site Guardian', description:'Runs the guarded site review workflow and prepares evidence. No production deployment.', repo:'Raven-Sharp-QA-Agent', workflow:'raven-guardian-dispatch.yml', ref:'main', safeRun:true, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Manual', risk:'low' },

  // All six Raven Sharp SaaS products expose a safe, manual test control.
  { id:'pod-tests', group:'saas', label:'POD Suite tests', description:'Runs the existing read-only Test and Build Pipeline for POD Suite.', repo:'Raven-Sharp-POD-Automation', workflow:'test-and-build.yml', ref:'main', safeRun:true, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Manual test', risk:'low' },
  { id:'image-optimiser-tests', group:'saas', label:'Image Optimiser tests', description:'Runs the existing read-only Test and Build Pipeline for Image Optimiser & Upscaler.', repo:'Raven-Sharp-Image-Optimiser-Upscaler', workflow:'test-and-build.yml', ref:'main', safeRun:true, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Manual test', risk:'low' },
  { id:'ad-manager-tests', group:'saas', label:'Ad Manager tests', description:'Runs the existing read-only Test and Build Pipeline for Ad Manager.', repo:'Raven-Sharp-Ad-Manager', workflow:'test-and-build.yml', ref:'main', safeRun:true, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Manual test', risk:'low' },
  { id:'book-creator-tests', group:'saas', label:'Book Creator tests', description:'Runs the existing read-only Test and Build Pipeline for Book Creator.', repo:'Raven-Sharp-Book-Creator', workflow:'test-and-build.yml', ref:'main', safeRun:true, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Manual test', risk:'low' },
  { id:'content-creator-tests', group:'saas', label:'Content Creator tests', description:'Runs the existing read-only Test and Build Pipeline for Content Creator.', repo:'Raven-Sharp-Content-Creator', workflow:'test-and-build.yml', ref:'main', safeRun:true, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Manual test', risk:'low' },
  { id:'smart-cleaner-tests', group:'saas', label:'Smart Cleaner backend tests', description:'Runs the existing Railway verification workflow with its isolated CI Mongo service and Docker build.', repo:'Raven-Sharp-Smart-AI-Cleaner', workflow:'verify-railway-deploy.yml', ref:'main', safeRun:true, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Manual test', risk:'low' },

  { id:'automation-6', group:'automation-health', label:'Automation & infrastructure health', description:'Read-only repository, build, SEO, link and regression evidence for the Hub.', repo:'ascension-automation-hub', workflow:'automation-6.yml', ref:'main', safeRun:true, schedulable:false, scheduleLocked:true, defaultFrequency:'weekly', nativeSchedule:'Weekly · GitHub managed', risk:'low' },
  { id:'store-ops', group:'store-listings', label:'Etsy Store Ops', description:'Phone-friendly Etsy draft listing and listing-management app. Publishing is intentionally unavailable.', repo:'Raven-Sharp-Store-Ops', workflow:null, ref:'main', controlType:'external-app', envUrl:'STORE_OPS_URL', safeRun:false, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Open app when needed', risk:'medium', gated:true },
  { id:'saas-maintainer', group:'saas', label:'SaaS repair agent', description:'Prepares branch-only Raven SaaS repair work and draft review evidence.', repo:'Raven-Sharp-QA-Agent', workflow:'raven-saas-maintainer.lock.yml', ref:'main', safeRun:false, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Manual approval', risk:'medium', gated:true },
  { id:'marketing-worker', group:'marketing-assets', label:'Marketing pack worker', description:'Prepares campaign copy and marketing assets. It does not launch ads, send messages or change budgets.', repo:'Raven-Sharp-QA-Agent', workflow:'raven-marketing-worker.lock.yml', ref:'main', safeRun:false, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Manual brief', risk:'medium', gated:true },
  { id:'affiliate-scout', group:'marketing-assets', label:'Affiliate scout', description:'Prepares affiliate research for review. Publishing and account changes stay manual.', repo:'Raven-Sharp-QA-Agent', workflow:'raven-affiliate-scout.lock.yml', ref:'main', safeRun:false, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Manual review', risk:'medium', gated:true },
  { id:'art-marketplace', group:'marketing-assets', label:'Art marketplace agent', description:'Prepares Fine Art America / ArtPal work. Publishing remains separately approved.', repo:'Raven-Sharp-QA-Agent', workflow:'raven-art-marketplace-agent.yml', ref:'main', safeRun:false, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Manual approval', risk:'medium', gated:true },
  { id:'adg-worker-deploy', group:'site-adsense', label:'AdSense monitor deployment', description:'Production deployment for the ADG monitor worker. Review and approval required.', repo:'ADG-MONITOR-V4', workflow:'deploy-adg-worker.yml', ref:'main', safeRun:false, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Manual approval', risk:'high', gated:true },
  { id:'saas-worker-deploy', group:'saas', label:'SaaS monitor deployment', description:'Production deployment for the SaaS monitor worker. Review and approval required.', repo:'ADG-MONITOR-V4', workflow:'deploy-saas-worker.yml', ref:'main', safeRun:false, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Manual approval', risk:'high', gated:true },
  { id:'hub-release', group:'automation-health', label:'Management Hub release', description:'The Hub uses its dedicated Check → Test → Preview → Review → Deploy lane above.', repo:'ascension-automation-hub', workflow:'hub-release-gate.yml', ref:'main', safeRun:false, schedulable:false, defaultFrequency:'manual', nativeSchedule:'Guided release lane', risk:'high', gated:true }
];

const FREQUENCY_MS = { '6h': 6 * 60 * 60 * 1000, daily: 24 * 60 * 60 * 1000, weekly: 7 * 24 * 60 * 60 * 1000 };
export const FRIENDLY_FREQUENCIES = new Set(['6h','daily','weekly','manual']);
export function automationById(id){ return AUTOMATIONS.find((item)=>item.id===id)||null; }
export function nextRunAt(frequency,from=new Date()){ if(frequency==='manual')return null; const ms=FREQUENCY_MS[frequency]; return ms?new Date(from.getTime()+ms).toISOString():null; }

async function github(path,token,options={}){
  if(!token) throw Object.assign(new Error('GitHub token is not configured'),{status:503});
  const response=await fetch(`https://api.github.com${path}`,{method:options.method||'GET',headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'User-Agent':'Ascension-Automation-Hub/1.0','X-GitHub-Api-Version':'2022-11-28',...(options.body?{'Content-Type':'application/json'}:{})},body:options.body?JSON.stringify(options.body):undefined});
  if(response.status===204)return null; const payload=await response.json().catch(()=>({})); if(!response.ok){const error=new Error(payload.message||`GitHub API returned ${response.status}`);error.status=response.status;throw error;} return payload;
}
export async function dispatchAutomation(automation,token,inputs={}){ if(!automation?.safeRun)throw Object.assign(new Error('This action requires the gated review path and cannot be started by the generic Run now control.'),{status:409}); if(!automation.workflow)throw Object.assign(new Error('This control opens an external app and has no GitHub workflow to dispatch.'),{status:409}); await github(`/repos/${OWNER}/${automation.repo}/actions/workflows/${encodeURIComponent(automation.workflow)}/dispatches`,token,{method:'POST',body:{ref:automation.ref,...(Object.keys(inputs).length?{inputs}:{})}}); return {requested:true,repository:automation.repo,workflow:automation.workflow,ref:automation.ref}; }
async function latestRun(automation,token){ if(!automation.workflow)return {state:automation.controlType==='external-app'?'external':'manual',run:null}; try{const payload=await github(`/repos/${OWNER}/${automation.repo}/actions/workflows/${encodeURIComponent(automation.workflow)}/runs?per_page=1`,token);const run=payload.workflow_runs?.[0];if(!run)return {state:'no-runs',run:null};return {state:run.status==='completed'?(run.conclusion||'unknown'):run.status,run:{id:run.id,status:run.status,conclusion:run.conclusion,event:run.event,branch:run.head_branch,createdAt:run.created_at,updatedAt:run.updated_at,url:run.html_url}};}catch(error){return {state:'unavailable',run:null,warning:error.message};} }
async function scheduleMap(db){if(!db)return new Map();try{const result=await db.prepare('SELECT automation_id, frequency, paused, managed_by_hub, last_run_at, next_run_at, last_status, updated_at FROM automation_schedules').all();return new Map((result.results||[]).map((row)=>[row.automation_id,row]));}catch{return new Map();}}
export async function listAutomationState(env){const readToken=env?.GITHUB_READ_TOKEN||env?.GITHUB_CONTROL_TOKEN;const schedules=await scheduleMap(env?.HUB_DB);const items=await Promise.all(AUTOMATIONS.map(async(automation)=>{const live=readToken?await latestRun(automation,readToken):{state:automation.workflow?'unavailable':'external',run:null,warning:automation.workflow?'GitHub read token is not configured':null};const stored=schedules.get(automation.id);const schedule=stored?{frequency:stored.frequency,paused:Boolean(stored.paused),managedByHub:Boolean(stored.managed_by_hub),lastRunAt:stored.last_run_at,nextRunAt:stored.next_run_at,lastStatus:stored.last_status,updatedAt:stored.updated_at,source:stored.managed_by_hub?'hub':'native'}:{frequency:automation.defaultFrequency,paused:false,managedByHub:false,lastRunAt:live.run?.createdAt||null,nextRunAt:null,lastStatus:live.state,updatedAt:null,source:'native',label:automation.nativeSchedule};const externalUrl=automation.envUrl?env?.[automation.envUrl]||null:null;return {...automation,externalUrl,live,schedule};}));return {generatedAt:new Date().toISOString(),connections:{githubRead:Boolean(readToken),githubControl:Boolean(env?.GITHUB_CONTROL_TOKEN),database:Boolean(env?.HUB_DB),schedulerKey:Boolean(env?.HUB_SCHEDULER_KEY)},items};}
export async function upsertSchedule(db,automation,frequency,paused,managedByHub=true){if(!db)throw Object.assign(new Error('Hub database binding is unavailable'),{status:503});if(!FRIENDLY_FREQUENCIES.has(frequency))throw Object.assign(new Error('Unsupported schedule'),{status:400});if(automation.scheduleLocked)throw Object.assign(new Error(`This schedule is already managed by its GitHub workflow (${automation.nativeSchedule}). Hub takeover is blocked to prevent duplicate runs.`),{status:409});if(!automation.schedulable)throw Object.assign(new Error('This automation is intentionally manual'),{status:409});const now=new Date();const next=paused||frequency==='manual'?null:nextRunAt(frequency,now);await db.prepare(`INSERT INTO automation_schedules (automation_id, frequency, paused, managed_by_hub, next_run_at, updated_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6) ON CONFLICT(automation_id) DO UPDATE SET frequency=excluded.frequency, paused=excluded.paused, managed_by_hub=excluded.managed_by_hub, next_run_at=excluded.next_run_at, updated_at=excluded.updated_at`).bind(automation.id,frequency,paused?1:0,managedByHub?1:0,next,now.toISOString()).run();return {automationId:automation.id,frequency,paused,managedByHub,nextRunAt:next};}
export async function recordAutomationAction(db,automationId,action,status,payload={},actor='owner'){if(!db)return null;const actionId=crypto.randomUUID();const recordedAt=new Date().toISOString();await db.prepare('INSERT INTO automation_actions (action_id, automation_id, action, actor, status, recorded_at, payload_json) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)').bind(actionId,automationId,action,actor,status,recordedAt,JSON.stringify(payload)).run();return {actionId,recordedAt};}
