// Generated by scripts/build-hub-pages.mjs; do not edit.
export const dashboardSnapshot = {
  "schemaVersion": "1.0.0",
  "generatedAt": "2026-09-03T18:02:19.044Z",
  "mode": "mixed",
  "source": "automation-6/report-v1 + configured adapters",
  "sourceWarnings": [
    "automation-1: configured result artifact is not available"
  ],
  "overview": {
    "status": "passed",
    "passed": 3,
    "warning": 0,
    "failed": 0,
    "skipped": 0,
    "approvals": 3,
    "attention": 4
  },
  "nextApproval": {
    "id": "deploy-management-hub-2026-08-30T12-21-37-158Z-10568",
    "action": "Approve Management Hub deployment handoff",
    "reason": "Local Hub health, metadata, and the complete automated test suite were rechecked. Approval authorizes a separate deployment step; it does not deploy automatically.",
    "risk": "medium",
    "status": "pending",
    "capturedAt": "2026-08-30T12:21:38.076Z",
    "evidenceStatus": "passed",
    "knownFailures": 0,
    "evidenceRefs": [
      {
        "label": "Recheck evidence",
        "url": "/#activity"
      },
      {
        "label": "Worker run details",
        "url": "/#worker-evidence"
      }
    ],
    "priority": 0,
    "provenance": "live",
    "workerId": "automation-6",
    "approvalEligible": true,
    "approvalBlockers": []
  },
  "nextTask": null,
  "businesses": [
    {
      "id": "ascension-digital",
      "name": "Ascension Digital",
      "type": "Portfolio",
      "status": "passed",
      "projects": 3
    },
    {
      "id": "raven-sharp",
      "name": "Raven Sharp",
      "type": "Website",
      "status": "passed",
      "projects": 1
    }
  ],
  "runs": [
    {
      "id": "2026-08-30T12-21-37-158Z-10568",
      "automation": "Automation 6",
      "status": "passed",
      "startedAt": "2026-08-30T12:21:37.158Z",
      "finishedAt": "2026-08-30T12:21:38.076Z",
      "summary": {
        "passed": 3,
        "warning": 0,
        "failed": 0,
        "skipped": 0
      },
      "provenance": "live"
    },
    {
      "id": "fixture-automation-2-001",
      "automation": "Final review checks",
      "workerId": "automation-2",
      "status": "warning",
      "startedAt": "2026-08-22T00:10:00.000Z",
      "finishedAt": "2026-08-22T00:11:12.000Z",
      "summary": {
        "passed": 2,
        "warning": 1,
        "failed": 0,
        "skipped": 0
      },
      "provenance": "fixture"
    }
  ],
  "activity": [
    {
      "id": "39c14fec-cc69-4d56-852b-195a40ac9efc",
      "title": "Code edit requested: Add guarded repair intake",
      "kind": "repair-requested",
      "status": "warning",
      "at": "2026-09-03T18:02:10.828Z",
      "durationMs": 0,
      "evidence": {
        "actor": "local-owner"
      },
      "provenance": "local"
    },
    {
      "id": "62ba71e4-7239-42a0-bf8c-e40d5aaf2fa0",
      "title": "Management Hub deployment succeeded: deploy-management-hub-2026-09-03T17-19-48-466Z-18588",
      "kind": "deployment-execution-succeeded",
      "status": "warning",
      "at": "2026-09-03T17:27:42.100Z",
      "durationMs": 0,
      "evidence": {
        "approvalId": "deploy-management-hub-2026-09-03T17-19-48-466Z-18588",
        "actor": "local-owner"
      },
      "provenance": "local"
    },
    {
      "id": "6036f296-8654-4c61-b440-e0edb33548d8",
      "title": "Management Hub deployment started: deploy-management-hub-2026-09-03T17-19-48-466Z-18588",
      "kind": "deployment-execution-started",
      "status": "warning",
      "at": "2026-09-03T17:27:26.985Z",
      "durationMs": 0,
      "evidence": {
        "approvalId": "deploy-management-hub-2026-09-03T17-19-48-466Z-18588",
        "actor": "local-owner"
      },
      "provenance": "local"
    },
    {
      "id": "49f89264-3a43-4a35-84e5-4d305eee71f8",
      "title": "Approval approved: deploy-management-hub-2026-09-03T17-19-48-466Z-18588",
      "kind": "approval-decision",
      "status": "passed",
      "at": "2026-09-03T17:27:21.570Z",
      "durationMs": 0,
      "evidence": {
        "decision": "approved",
        "approvalId": "deploy-management-hub-2026-09-03T17-19-48-466Z-18588",
        "actor": "local-owner"
      },
      "provenance": "local"
    },
    {
      "id": "management-hub-tests",
      "title": "Management Hub Tests",
      "kind": "regression",
      "status": "passed",
      "at": "2026-08-30T12:21:37.247Z",
      "durationMs": 830,
      "evidence": {
        "exitCode": 0,
        "signal": null,
        "stdout": "✔ accepts a minimal safe config (3.2259ms)\n✔ rejects shell-enabled commands (1.0246ms)\n✔ rejects non-http targets (0.4841ms)\n✔ evidence adapter preserves immutable snapshot provenance (19.2472ms)\n✔ missing snapshot degrades independently without claiming live status (12.3409ms)\n✔ append-only local history remains reviewable and skips corrupt lines (29.0167ms)\n✔ worker registry ingests report-v1 fixtures and degrades missing live indexes (88.5996ms)\n✔ history export, lossless retention archive, and idempotent import preserve event provenance (90.7358ms)\n✔ Pages dashboard requires D1 and preserves snapshot provenance (80.9061ms)\n✔ Pages decision endpoint validates input and writes decision plus history atomically (13.8296ms)\n✔ hub serves static files with restrictive local security headers and query strings (110.9861ms)\n✔ hub returns actionable client errors without mutating state (51.1548ms)\n✔ latest run UI labels pass rate and evidence provenance explicitly (8.1675ms)\n✔ manual recheck is prominent and restricted to the local Hub (38.4526ms)\n✔ file adapter loads a versioned source and exposes fixture provenance (40.8091ms)\n✔ source failures degrade independently and remain visible as warnings (8.8676ms)\n✔ hub builds a safe demonstration dashboard without run artifacts (56.9802ms)\n✔ hub ingests Automation 6 report-v1 and preserves evidence (23.6722ms)\n✔ owner review blocks fixture approval and permits a local changes request (43.4744ms)\n✔ hub can read an Automation 6 index from another worktree (24.1846ms)\n✔ health, SEO and broken-link checks work against a local site (101.3248ms)\n✔ Management Hub index is atomically updated and deduplicated (16.0942ms)\n✔ orchestration registry shares the production permission contract (19.4783ms)\nℹ tests 23\nℹ suites 0\nℹ pass 23\nℹ fail 0\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 667.2214\n",
        "stderr": ""
      },
      "provenance": "live"
    },
    {
      "id": "management-hub",
      "title": "Management Hub",
      "kind": "health",
      "status": "passed",
      "at": "2026-08-30T12:21:37.163Z",
      "durationMs": 82,
      "evidence": {
        "url": "http://127.0.0.1:4175/",
        "finalUrl": "http://127.0.0.1:4175/",
        "statusCode": 200,
        "contentType": "text/html; charset=utf-8"
      },
      "provenance": "live"
    },
    {
      "id": "management-hub",
      "title": "Management Hub",
      "kind": "seo",
      "status": "passed",
      "at": "2026-08-30T12:21:37.163Z",
      "durationMs": 84,
      "evidence": {
        "url": "http://127.0.0.1:4175/",
        "finalUrl": "http://127.0.0.1:4175/",
        "statusCode": 200,
        "contentType": "text/html; charset=utf-8",
        "title": "Ascension Digital — Management Hub",
        "description": "Local Ascension Digital operations, evidence, and owner approvals dashboard.",
        "canonical": "http://127.0.0.1:4175/",
        "missing": []
      },
      "provenance": "live"
    },
    {
      "id": "15292aa9-a53d-48ea-9b82-7cf962051c06",
      "title": "Approval approved: approve-raven-post",
      "kind": "approval-decision",
      "status": "passed",
      "at": "2026-08-29T17:11:47.105Z",
      "durationMs": 0,
      "evidence": {
        "decision": "approved",
        "approvalId": "approve-raven-post",
        "actor": "local-owner"
      },
      "provenance": "local"
    },
    {
      "id": "0d488db5-12ac-496a-9e95-80b123ec58ae",
      "title": "Approval approved: approve-checkout-deploy",
      "kind": "approval-decision",
      "status": "passed",
      "at": "2026-08-29T17:11:39.446Z",
      "durationMs": 0,
      "evidence": {
        "decision": "approved",
        "approvalId": "approve-checkout-deploy",
        "actor": "local-owner"
      },
      "provenance": "local"
    },
    {
      "id": "5322ff25-3e3a-4db8-bc80-ae6b1197a4a6",
      "title": "Approval approved: deploy-lead-engine-repair",
      "kind": "approval-decision",
      "status": "passed",
      "at": "2026-08-29T17:11:31.525Z",
      "durationMs": 0,
      "evidence": {
        "decision": "approved",
        "approvalId": "deploy-lead-engine-repair",
        "actor": "local-owner"
      },
      "provenance": "local"
    },
    {
      "id": "content-owner-review",
      "title": "Content Owner Review",
      "kind": "content-approval",
      "status": "warning",
      "at": "2026-08-22T00:10:08.000Z",
      "durationMs": 12,
      "evidence": {
        "pending": 1,
        "fixture": true
      },
      "provenance": "fixture",
      "workerId": "automation-2"
    },
    {
      "id": "content-draft-generation",
      "title": "Content Draft Generation",
      "kind": "content-generation",
      "status": "passed",
      "at": "2026-08-22T00:10:00.000Z",
      "durationMs": 2400,
      "evidence": {
        "generated": 2,
        "fixture": true
      },
      "provenance": "fixture",
      "workerId": "automation-2"
    }
  ],
  "approvals": [
    {
      "id": "deploy-management-hub-2026-08-30T12-21-37-158Z-10568",
      "action": "Approve Management Hub deployment handoff",
      "reason": "Local Hub health, metadata, and the complete automated test suite were rechecked. Approval authorizes a separate deployment step; it does not deploy automatically.",
      "risk": "medium",
      "status": "pending",
      "capturedAt": "2026-08-30T12:21:38.076Z",
      "evidenceStatus": "passed",
      "knownFailures": 0,
      "evidenceRefs": [
        {
          "label": "Recheck evidence",
          "url": "/#activity"
        },
        {
          "label": "Worker run details",
          "url": "/#worker-evidence"
        }
      ],
      "priority": 0,
      "provenance": "live",
      "workerId": "automation-6",
      "approvalEligible": true,
      "approvalBlockers": []
    },
    {
      "id": "automation-2-post-approval",
      "action": "Approve generated Raven Sharp post",
      "reason": "Fixture content result is ready for owner review.",
      "risk": "low",
      "status": "pending",
      "priority": 3,
      "provenance": "fixture",
      "workerId": "automation-2",
      "evidenceRefs": [],
      "knownFailures": null,
      "approvalEligible": false,
      "approvalBlockers": [
        "fixture evidence is not current live evidence",
        "capture time is missing",
        "no review evidence is attached",
        "evidence has not passed",
        "known-failure count is missing"
      ]
    },
    {
      "id": "automation-1-authenticated-fixture",
      "action": "Approve a dedicated non-production Raven Sharp test tenant",
      "reason": "Required to verify owner access, generation, persistence, downloads, checkout boundaries and provider drafts without touching production data.",
      "risk": "medium",
      "status": "pending",
      "priority": 4,
      "provenance": "snapshot",
      "sourceRef": "d5ed6f2d891c3bdab378623030f7786bfdee689f",
      "workerId": "automation-1",
      "evidenceRefs": [],
      "knownFailures": null,
      "approvalEligible": false,
      "approvalBlockers": [
        "snapshot evidence is not current live evidence",
        "capture time is missing",
        "no review evidence is attached",
        "evidence has not passed",
        "known-failure count is missing"
      ]
    }
  ],
  "approvedDeployment": null,
  "runReviews": [],
  "decisionHistory": [
    {
      "schemaVersion": "1.0.0",
      "eventId": "49f89264-3a43-4a35-84e5-4d305eee71f8",
      "recordedAt": "2026-09-03T17:27:21.570Z",
      "type": "approval-decision",
      "title": "Approval approved: deploy-management-hub-2026-09-03T17-19-48-466Z-18588",
      "approvalId": "deploy-management-hub-2026-09-03T17-19-48-466Z-18588",
      "decision": "approved",
      "actor": "local-owner",
      "provenance": "local"
    },
    {
      "schemaVersion": "1.0.0",
      "eventId": "15292aa9-a53d-48ea-9b82-7cf962051c06",
      "recordedAt": "2026-08-29T17:11:47.105Z",
      "type": "approval-decision",
      "title": "Approval approved: approve-raven-post",
      "approvalId": "approve-raven-post",
      "decision": "approved",
      "actor": "local-owner",
      "provenance": "local"
    },
    {
      "schemaVersion": "1.0.0",
      "eventId": "0d488db5-12ac-496a-9e95-80b123ec58ae",
      "recordedAt": "2026-08-29T17:11:39.446Z",
      "type": "approval-decision",
      "title": "Approval approved: approve-checkout-deploy",
      "approvalId": "approve-checkout-deploy",
      "decision": "approved",
      "actor": "local-owner",
      "provenance": "local"
    },
    {
      "schemaVersion": "1.0.0",
      "eventId": "5322ff25-3e3a-4db8-bc80-ae6b1197a4a6",
      "recordedAt": "2026-08-29T17:11:31.525Z",
      "type": "approval-decision",
      "title": "Approval approved: deploy-lead-engine-repair",
      "approvalId": "deploy-lead-engine-repair",
      "decision": "approved",
      "actor": "local-owner",
      "provenance": "local"
    }
  ],
  "evidenceCoverage": {
    "state": "live-plus-snapshots",
    "canonicalLiveAvailable": true,
    "snapshots": [
      {
        "source": "automation-1",
        "sourceId": "automation-1-raven-audit",
        "capturedAt": "2026-08-22T12:11:34+10:00",
        "sourceRef": "d5ed6f2d891c3bdab378623030f7786bfdee689f",
        "mode": "snapshot",
        "items": [
          {
            "id": "image-optimiser",
            "label": "Image Optimiser & Upscaler",
            "status": "passed-with-warning",
            "summary": "Build and public health passed; paid generation, download and owner session remain unproved.",
            "coverage": "public-and-build"
          },
          {
            "id": "pod-suite",
            "label": "POD suite",
            "status": "passed-with-warning",
            "summary": "Build and public health passed; provider publishing remains blocked and unproved.",
            "coverage": "public-and-build"
          },
          {
            "id": "ad-manager",
            "label": "Ad Manager",
            "status": "passed-with-warning",
            "summary": "Smoke tests and health passed; deployment documentation is stale.",
            "coverage": "public-and-build"
          },
          {
            "id": "book-creator",
            "label": "Book Creator",
            "status": "passed-with-warning",
            "summary": "Public page and API passed; authenticated generation and exports remain unproved.",
            "coverage": "public-only"
          },
          {
            "id": "content-creator",
            "label": "Content Creator",
            "status": "passed-with-warning",
            "summary": "Public page and API passed; naming is inconsistent and authenticated generation remains unproved.",
            "coverage": "public-only"
          },
          {
            "id": "smart-cleaner-web",
            "label": "Smart Cleaner web SaaS",
            "status": "passed-with-warning",
            "summary": "Marketing surface passed; no functional connected-drive backend was evidenced.",
            "coverage": "public-only"
          },
          {
            "id": "raven-hub",
            "label": "RavenSharp.com hub",
            "status": "warning",
            "summary": "Direct HTTPS returned 200, while the audit browser encountered a DNS warning.",
            "coverage": "conflicting-runtime-evidence"
          }
        ]
      }
    ],
    "snapshotItemCount": 7
  },
  "queues": {
    "content": [
      {
        "id": "content-raven-weekly",
        "title": "Raven Sharp weekly insight",
        "channel": "LinkedIn",
        "status": "awaiting-approval",
        "scheduledFor": "2026-08-24T23:00:00.000Z",
        "owner": "Content agent",
        "provenance": "fixture"
      },
      {
        "id": "content-ascension-case-study",
        "title": "Automation case study",
        "channel": "Website",
        "status": "draft",
        "scheduledFor": null,
        "owner": "Growth agent",
        "provenance": "fixture"
      }
    ],
    "assets": [
      {
        "id": "asset-raven-home-preview",
        "title": "Raven Sharp homepage preview",
        "type": "screenshot",
        "status": "ready",
        "preview": "/previews/raven-home.png",
        "business": "Raven Sharp",
        "provenance": "fixture"
      },
      {
        "id": "asset-ascension-campaign",
        "title": "Ascension campaign creative",
        "type": "image",
        "status": "review",
        "preview": null,
        "business": "Ascension Digital",
        "provenance": "fixture"
      }
    ],
    "repairs": [
      {
        "id": "repair-checkout-handoff",
        "title": "Repair checkout handoff regression",
        "status": "branch-ready",
        "priority": "critical",
        "branch": "codex/repair-checkout-handoff",
        "tests": {
          "passed": 18,
          "failed": 0
        },
        "preview": null,
        "provenance": "fixture"
      },
      {
        "id": "repair-meta-description",
        "title": "Improve Ascension meta description",
        "status": "suggested",
        "priority": "medium",
        "branch": null,
        "tests": null,
        "preview": null,
        "provenance": "fixture"
      }
    ],
    "finance": [
      {
        "id": "finance-income-aug",
        "label": "August income",
        "category": "income",
        "amount": 8420,
        "currency": "AUD",
        "status": "estimated",
        "provenance": "fixture"
      },
      {
        "id": "finance-expenses-aug",
        "label": "August operating expenses",
        "category": "expense",
        "amount": 2310,
        "currency": "AUD",
        "status": "estimated",
        "provenance": "fixture"
      },
      {
        "id": "finance-tax-quarter",
        "label": "Quarterly tax records",
        "category": "tax",
        "amount": 0,
        "currency": "AUD",
        "status": "needs-reconciliation",
        "provenance": "fixture"
      }
    ]
  },
  "financeSummary": {
    "currency": "AUD",
    "income": 8420,
    "expenses": 2310,
    "net": 6110,
    "needsReconciliation": 1,
    "provenance": "fixture"
  },
  "modules": [
    {
      "id": "projects",
      "label": "Projects",
      "count": 3,
      "state": "active"
    },
    {
      "id": "monitors",
      "label": "Monitors & tests",
      "count": 3,
      "state": "live"
    },
    {
      "id": "audit-evidence",
      "label": "Audit evidence",
      "count": 7,
      "state": "snapshot"
    },
    {
      "id": "content",
      "label": "Content approvals",
      "count": 1,
      "state": "fixture"
    },
    {
      "id": "assets",
      "label": "Assets & previews",
      "count": 2,
      "state": "fixture"
    },
    {
      "id": "repairs",
      "label": "Branch-ready repairs",
      "count": 1,
      "state": "fixture"
    },
    {
      "id": "finance",
      "label": "Finance & tax",
      "count": 3,
      "state": "fixture"
    }
  ]
};
export const workerSnapshots = {};
