// Generated by scripts/build-hub-pages.mjs; do not edit.
export const dashboardSnapshot = {
  "schemaVersion": "1.0.0",
  "generatedAt": "2026-08-30T05:51:49.081Z",
  "mode": "demonstration",
  "source": "demonstration report + configured fixture/snapshot adapters",
  "sourceWarnings": [
    "automation-6: configured result artifact is not available"
  ],
  "overview": {
    "status": "warning",
    "passed": 12,
    "warning": 2,
    "failed": 1,
    "skipped": 1,
    "approvals": 2,
    "attention": 6
  },
  "nextApproval": {
    "id": "automation-2-post-approval",
    "action": "Approve generated Raven Sharp post",
    "reason": "Fixture content result is ready for owner review.",
    "risk": "low",
    "status": "pending",
    "priority": 3,
    "provenance": "fixture",
    "workerId": "automation-2",
    "evidenceRefs": [],
    "knownFailures": null,
    "approvalEligible": false,
    "approvalBlockers": [
      "fixture evidence is not current live evidence",
      "capture time is missing",
      "no review evidence is attached",
      "evidence has not passed",
      "known-failure count is missing"
    ]
  },
  "nextTask": {
    "id": "lead-engine-regression",
    "title": "Lead Engine Regression",
    "status": "failed",
    "detail": "Checkout handoff assertion failed",
    "rank": 0,
    "provenance": "fixture"
  },
  "businesses": [
    {
      "id": "ascension-digital",
      "name": "Ascension Digital",
      "type": "Portfolio",
      "status": "warning",
      "projects": 3
    },
    {
      "id": "raven-sharp",
      "name": "Raven Sharp",
      "type": "Website",
      "status": "passed",
      "projects": 1
    }
  ],
  "runs": [
    {
      "id": "demo-ascension-001",
      "automation": "Automation 6",
      "status": "warning",
      "startedAt": "2026-08-30T05:48:57.036Z",
      "finishedAt": "2026-08-30T05:51:49.036Z",
      "summary": {
        "passed": 12,
        "warning": 2,
        "failed": 1,
        "skipped": 1
      },
      "provenance": "fixture"
    },
    {
      "id": "fixture-automation-2-001",
      "automation": "Content operations",
      "workerId": "automation-2",
      "status": "warning",
      "startedAt": "2026-08-22T00:10:00.000Z",
      "finishedAt": "2026-08-22T00:11:12.000Z",
      "summary": {
        "passed": 2,
        "warning": 1,
        "failed": 0,
        "skipped": 0
      },
      "provenance": "fixture"
    }
  ],
  "activity": [
    {
      "id": "raven-sharp-production-health",
      "title": "Raven Sharp Production Health",
      "kind": "health",
      "status": "passed",
      "at": "2026-08-30T05:51:49.036Z",
      "durationMs": 684,
      "evidence": {
        "httpStatus": 200,
        "contentType": "text/html"
      },
      "provenance": "fixture"
    },
    {
      "id": "ascension-digital-seo",
      "title": "Ascension Digital Seo",
      "kind": "seo",
      "status": "warning",
      "at": "2026-08-30T05:51:49.036Z",
      "durationMs": 391,
      "evidence": {
        "warning": "Meta description needs attention"
      },
      "provenance": "fixture"
    },
    {
      "id": "lead-engine-regression",
      "title": "Lead Engine Regression",
      "kind": "test",
      "status": "failed",
      "at": "2026-08-30T05:51:49.036Z",
      "durationMs": 4218,
      "evidence": {
        "exitCode": 1,
        "summary": "Checkout handoff assertion failed"
      },
      "provenance": "fixture"
    },
    {
      "id": "raven-sharp-link-check",
      "title": "Raven Sharp Link Check",
      "kind": "links",
      "status": "passed",
      "at": "2026-08-30T05:51:49.036Z",
      "durationMs": 1224,
      "evidence": {
        "checked": 28,
        "failed": 0
      },
      "provenance": "fixture"
    },
    {
      "id": "weekly-screenshot-capture",
      "title": "Weekly Screenshot Capture",
      "kind": "screenshots",
      "status": "skipped",
      "at": "2026-08-30T05:51:49.036Z",
      "durationMs": 0,
      "evidence": {
        "reason": "Renderer not configured"
      },
      "provenance": "fixture"
    },
    {
      "id": "15292aa9-a53d-48ea-9b82-7cf962051c06",
      "title": "Approval approved: approve-raven-post",
      "kind": "approval-decision",
      "status": "passed",
      "at": "2026-08-29T17:11:47.105Z",
      "durationMs": 0,
      "evidence": {
        "decision": "approved",
        "approvalId": "approve-raven-post",
        "actor": "local-owner"
      },
      "provenance": "local"
    },
    {
      "id": "0d488db5-12ac-496a-9e95-80b123ec58ae",
      "title": "Approval approved: approve-checkout-deploy",
      "kind": "approval-decision",
      "status": "passed",
      "at": "2026-08-29T17:11:39.446Z",
      "durationMs": 0,
      "evidence": {
        "decision": "approved",
        "approvalId": "approve-checkout-deploy",
        "actor": "local-owner"
      },
      "provenance": "local"
    },
    {
      "id": "5322ff25-3e3a-4db8-bc80-ae6b1197a4a6",
      "title": "Approval approved: deploy-lead-engine-repair",
      "kind": "approval-decision",
      "status": "passed",
      "at": "2026-08-29T17:11:31.525Z",
      "durationMs": 0,
      "evidence": {
        "decision": "approved",
        "approvalId": "deploy-lead-engine-repair",
        "actor": "local-owner"
      },
      "provenance": "local"
    },
    {
      "id": "content-owner-review",
      "title": "Content Owner Review",
      "kind": "content-approval",
      "status": "warning",
      "at": "2026-08-22T00:10:08.000Z",
      "durationMs": 12,
      "evidence": {
        "pending": 1,
        "fixture": true
      },
      "provenance": "fixture",
      "workerId": "automation-2"
    },
    {
      "id": "content-draft-generation",
      "title": "Content Draft Generation",
      "kind": "content-generation",
      "status": "passed",
      "at": "2026-08-22T00:10:00.000Z",
      "durationMs": 2400,
      "evidence": {
        "generated": 2,
        "fixture": true
      },
      "provenance": "fixture",
      "workerId": "automation-2"
    }
  ],
  "approvals": [
    {
      "id": "automation-2-post-approval",
      "action": "Approve generated Raven Sharp post",
      "reason": "Fixture content result is ready for owner review.",
      "risk": "low",
      "status": "pending",
      "priority": 3,
      "provenance": "fixture",
      "workerId": "automation-2",
      "evidenceRefs": [],
      "knownFailures": null,
      "approvalEligible": false,
      "approvalBlockers": [
        "fixture evidence is not current live evidence",
        "capture time is missing",
        "no review evidence is attached",
        "evidence has not passed",
        "known-failure count is missing"
      ]
    },
    {
      "id": "automation-1-authenticated-fixture",
      "action": "Approve a dedicated non-production Raven Sharp test tenant",
      "reason": "Required to verify owner access, generation, persistence, downloads, checkout boundaries and provider drafts without touching production data.",
      "risk": "medium",
      "status": "pending",
      "priority": 4,
      "provenance": "snapshot",
      "sourceRef": "d5ed6f2d891c3bdab378623030f7786bfdee689f",
      "workerId": "automation-1",
      "evidenceRefs": [],
      "knownFailures": null,
      "approvalEligible": false,
      "approvalBlockers": [
        "snapshot evidence is not current live evidence",
        "capture time is missing",
        "no review evidence is attached",
        "evidence has not passed",
        "known-failure count is missing"
      ]
    }
  ],
  "runReviews": [],
  "decisionHistory": [
    {
      "schemaVersion": "1.0.0",
      "eventId": "15292aa9-a53d-48ea-9b82-7cf962051c06",
      "recordedAt": "2026-08-29T17:11:47.105Z",
      "type": "approval-decision",
      "title": "Approval approved: approve-raven-post",
      "approvalId": "approve-raven-post",
      "decision": "approved",
      "actor": "local-owner",
      "provenance": "local"
    },
    {
      "schemaVersion": "1.0.0",
      "eventId": "0d488db5-12ac-496a-9e95-80b123ec58ae",
      "recordedAt": "2026-08-29T17:11:39.446Z",
      "type": "approval-decision",
      "title": "Approval approved: approve-checkout-deploy",
      "approvalId": "approve-checkout-deploy",
      "decision": "approved",
      "actor": "local-owner",
      "provenance": "local"
    },
    {
      "schemaVersion": "1.0.0",
      "eventId": "5322ff25-3e3a-4db8-bc80-ae6b1197a4a6",
      "recordedAt": "2026-08-29T17:11:31.525Z",
      "type": "approval-decision",
      "title": "Approval approved: deploy-lead-engine-repair",
      "approvalId": "deploy-lead-engine-repair",
      "decision": "approved",
      "actor": "local-owner",
      "provenance": "local"
    }
  ],
  "evidenceCoverage": {
    "state": "snapshot-only",
    "canonicalLiveAvailable": false,
    "snapshots": [
      {
        "source": "automation-1",
        "sourceId": "automation-1-raven-audit",
        "capturedAt": "2026-08-22T12:11:34+10:00",
        "sourceRef": "d5ed6f2d891c3bdab378623030f7786bfdee689f",
        "mode": "snapshot",
        "items": [
          {
            "id": "image-optimiser",
            "label": "Image Optimiser & Upscaler",
            "status": "passed-with-warning",
            "summary": "Build and public health passed; paid generation, download and owner session remain unproved.",
            "coverage": "public-and-build"
          },
          {
            "id": "pod-suite",
            "label": "POD suite",
            "status": "passed-with-warning",
            "summary": "Build and public health passed; provider publishing remains blocked and unproved.",
            "coverage": "public-and-build"
          },
          {
            "id": "ad-manager",
            "label": "Ad Manager",
            "status": "passed-with-warning",
            "summary": "Smoke tests and health passed; deployment documentation is stale.",
            "coverage": "public-and-build"
          },
          {
            "id": "book-creator",
            "label": "Book Creator",
            "status": "passed-with-warning",
            "summary": "Public page and API passed; authenticated generation and exports remain unproved.",
            "coverage": "public-only"
          },
          {
            "id": "content-creator",
            "label": "Content Creator",
            "status": "passed-with-warning",
            "summary": "Public page and API passed; naming is inconsistent and authenticated generation remains unproved.",
            "coverage": "public-only"
          },
          {
            "id": "smart-cleaner-web",
            "label": "Smart Cleaner web SaaS",
            "status": "passed-with-warning",
            "summary": "Marketing surface passed; no functional connected-drive backend was evidenced.",
            "coverage": "public-only"
          },
          {
            "id": "raven-hub",
            "label": "RavenSharp.com hub",
            "status": "warning",
            "summary": "Direct HTTPS returned 200, while the audit browser encountered a DNS warning.",
            "coverage": "conflicting-runtime-evidence"
          }
        ]
      }
    ],
    "snapshotItemCount": 7
  },
  "queues": {
    "content": [
      {
        "id": "content-raven-weekly",
        "title": "Raven Sharp weekly insight",
        "channel": "LinkedIn",
        "status": "awaiting-approval",
        "scheduledFor": "2026-08-24T23:00:00.000Z",
        "owner": "Content agent",
        "provenance": "fixture"
      },
      {
        "id": "content-ascension-case-study",
        "title": "Automation case study",
        "channel": "Website",
        "status": "draft",
        "scheduledFor": null,
        "owner": "Growth agent",
        "provenance": "fixture"
      }
    ],
    "assets": [
      {
        "id": "asset-raven-home-preview",
        "title": "Raven Sharp homepage preview",
        "type": "screenshot",
        "status": "ready",
        "preview": "/previews/raven-home.png",
        "business": "Raven Sharp",
        "provenance": "fixture"
      },
      {
        "id": "asset-ascension-campaign",
        "title": "Ascension campaign creative",
        "type": "image",
        "status": "review",
        "preview": null,
        "business": "Ascension Digital",
        "provenance": "fixture"
      }
    ],
    "repairs": [
      {
        "id": "repair-checkout-handoff",
        "title": "Repair checkout handoff regression",
        "status": "branch-ready",
        "priority": "critical",
        "branch": "codex/repair-checkout-handoff",
        "tests": {
          "passed": 18,
          "failed": 0
        },
        "preview": null,
        "provenance": "fixture"
      },
      {
        "id": "repair-meta-description",
        "title": "Improve Ascension meta description",
        "status": "suggested",
        "priority": "medium",
        "branch": null,
        "tests": null,
        "preview": null,
        "provenance": "fixture"
      }
    ],
    "finance": [
      {
        "id": "finance-income-aug",
        "label": "August income",
        "category": "income",
        "amount": 8420,
        "currency": "AUD",
        "status": "estimated",
        "provenance": "fixture"
      },
      {
        "id": "finance-expenses-aug",
        "label": "August operating expenses",
        "category": "expense",
        "amount": 2310,
        "currency": "AUD",
        "status": "estimated",
        "provenance": "fixture"
      },
      {
        "id": "finance-tax-quarter",
        "label": "Quarterly tax records",
        "category": "tax",
        "amount": 0,
        "currency": "AUD",
        "status": "needs-reconciliation",
        "provenance": "fixture"
      }
    ]
  },
  "financeSummary": {
    "currency": "AUD",
    "income": 8420,
    "expenses": 2310,
    "net": 6110,
    "needsReconciliation": 1,
    "provenance": "fixture"
  },
  "modules": [
    {
      "id": "projects",
      "label": "Projects",
      "count": 3,
      "state": "active"
    },
    {
      "id": "monitors",
      "label": "Monitors & tests",
      "count": 5,
      "state": "fixture"
    },
    {
      "id": "audit-evidence",
      "label": "Audit evidence",
      "count": 7,
      "state": "snapshot"
    },
    {
      "id": "content",
      "label": "Content approvals",
      "count": 1,
      "state": "fixture"
    },
    {
      "id": "assets",
      "label": "Assets & previews",
      "count": 2,
      "state": "fixture"
    },
    {
      "id": "repairs",
      "label": "Branch-ready repairs",
      "count": 1,
      "state": "fixture"
    },
    {
      "id": "finance",
      "label": "Finance & tax",
      "count": 3,
      "state": "fixture"
    }
  ]
};
export const workerSnapshots = {};
